FROM alpine:latest
RUN apk add --update redis
CMD ["redis-server"]

# docker build -t myapp
# docker run -it --rm --name my-running-app myapp
# docker run -it --rm --name my-running-app myapp bash
# docker run -it --rm --name my-running-app myapp redis-cli
