FROM alpine
COPY ./html_files /app/html
COPY sample.txt /app/sample.txt
ADD archive.zip /app
ADD https://en.wikipedia.org/static/images/mobile/copyright/wikipedia-wordmark-en.svg /app/images/wiki.svg
